export default {
  TABLE_COMPANIES_FETCH_STATUSES: 'TABLE_COMPANIES_FETCH_STATUSES',
  TABLE_COMPANIES_SET_DATA: 'TABLE_COMPANIES_SET_DATA',
  TABLE_COMPANIES_SET_TOTAL: 'TABLE_COMPANIES_SET_TOTAL',
  TABLE_COMPANIES_ERROR: 'TABLE_COMPANIES_ERROR',
  TABLE_COMPANIES_SET_LOADING: 'TABLE_COMPANIES_SET_LOADING',
  TABLE_COMPANIES_FETCH_DATA: 'TABLE_COMPANIES_FETCH_DATA',
  TABLE_COMPANIES_SAGA_ONSEARCH_ACTION: 'TABLE_COMPANIES_SAGA_ONSEARCH_ACTION',
};
