export default {
  TABLE_PRODUCTS_FETCH_STATUSES: 'TABLE_PRODUCTS_FETCH_STATUSES',
  TABLE_PRODUCTS_SET_DATA: 'TABLE_PRODUCTS_SET_DATA',
  TABLE_PRODUCTS_SET_TOTAL: 'TABLE_PRODUCTS_SET_TOTAL',
  TABLE_PRODUCTS_ERROR: 'TABLE_PRODUCTS_ERROR',
  TABLE_PRODUCTS_SET_LOADING: 'TABLE_PRODUCTS_SET_LOADING',
  TABLE_PRODUCTS_FETCH_DATA: 'TABLE_PRODUCTS_FETCH_DATA',
  TABLE_PRODUCTS_SAGA_ONSEARCH_ACTION: 'TABLE_PRODUCTS_SAGA_ONSEARCH_ACTION',
};
